export default {
  dev: ENVIRONMENT === 'development',
  donationRoot: 'https://donate.monospace.live',
  debug: false,
  layoutHints: false,
  public: (window.injected.TARGET === "public"),
  backend: window.injected.OVERRIDE_BACKEND_HOST,
  backendPort: window.injected.OVERRIDE_BACKEND_PORT,
  secureSocket: (window.location.protocol === 'https:'),
  nofeed: false,
  txDelay: 10000,
  donationsEnabled: true,
  messagesEnabled: true,
  alertDuration: 20000,
}
